using UnityEngine;
using System.Collections;
 

public class OrbitCamera2 : MonoBehaviour
{
  
 
 public Transform _target;
 
 public float _distance = 20.0f;
  
 //Control the speed of zooming and dezooming.
 public float _zoomStep = 1.0f;
  
 //The speed of the camera. Control how fast the camera will rotate.
 public float _xSpeed = 1f;
 public float _ySpeed = 1f;
  
 //The position of the cursor on the screen. Used to rotate the camera.
 private float _x = 0.0f;
 private float _y = 0.0f;
  
 //Distance vector. 
 private Vector3 _distanceVector;
  
 /**
  * Move the camera to its initial position.
  */
 void Start ()
 {
  _distanceVector = new Vector3(0.0f,0.0f,-_distance);
   
  Vector2 angles = this.transform.localEulerAngles;
  _x = angles.x;
  _y = angles.y;
     
  this.Rotate(_x, _y);
   
 }
 
 /**
  * Rotate the camera or zoom depending on the input of the player.
  */
 void LateUpdate()
 {
  if ( _target )
  {
   this.RotateControls();
   this.Zoom();
  }
 }
  
 /**
  * Rotate the camera when the first button of the mouse is pressed.
  * 
  */
 void RotateControls()
 {
  if ( Input.GetButton("Fire1") )
  {
   _x += Input.GetAxis("Mouse X") * _xSpeed;
   _y += -Input.GetAxis("Mouse Y")* _ySpeed;
      
   this.Rotate(_x,_y);
  }

  if (Input.GetKey("d"))
    {
      _x -= Time.deltaTime * _xSpeed*16f;
      this.Rotate(_x,_y);
    }

  if (Input.GetKey("a"))
    {
      _x += Time.deltaTime * _xSpeed*16f;
      this.Rotate(_x,_y);
    }

  if (Input.GetKey("s"))
    {
      _y -= Time.deltaTime * _ySpeed*16f;
      this.Rotate(_x,_y);
    }

  if (Input.GetKey("w"))
    {
      _y += Time.deltaTime * _ySpeed*16f;
      this.Rotate(_x,_y);
    }
  
  
 }
  
 /**
  * Transform the cursor mouvement in rotation and in a new position
  * for the camera.
  */
 void Rotate( float x, float y )
 {
  //Transform angle in degree in quaternion form used by Unity for rotation.
  Quaternion rotation = Quaternion.Euler(y,x,0.0f);
   
  //The new position is the target position + the distance vector of the camera
  //rotated at the specified angle.
  Vector3 position = rotation * _distanceVector + _target.position;
     
  //Update the rotation and position of the camera.
  transform.rotation = rotation;
  transform.position = position;
 }
  
 /**
  * Zoom or dezoom depending on the input of the mouse wheel.
  */
 void Zoom()
 {
  if ( Input.GetAxis("Mouse ScrollWheel") < 0.0f )
  {
   this.ZoomOut();
  }
  else if ( Input.GetAxis("Mouse ScrollWheel") > 0.0f )
  {
   this.ZoomIn();
  }

  if (Input.GetKey("e"))
    {
      this.ZoomInKey();
    }

  if (Input.GetKey("q"))
    {
      this.ZoomOutKey();
    }
 
 }
  
 /**
  * Reduce the distance from the camera to the target and
  * update the position of the camera (with the Rotate function).
  */
 void ZoomIn()
 {
  _distance -= _zoomStep;
  _distanceVector = new Vector3(0.0f,0.0f,-_distance);
  this.Rotate(_x,_y);
 }

 void ZoomInKey()
 {
  _distance -= _zoomStep*Time.deltaTime*3f;
  _distanceVector = new Vector3(0.0f,0.0f,-_distance);
  this.Rotate(_x,_y);
 }
  
 /**
  * Increase the distance from the camera to the target and
  * update the position of the camera (with the Rotate function).
  */
 void ZoomOut()
 {
  _distance += _zoomStep;
  _distanceVector = new Vector3(0.0f,0.0f,-_distance);
  this.Rotate(_x,_y);
 }

 void ZoomOutKey()
 {
  _distance += _zoomStep*Time.deltaTime*3f;
  _distanceVector = new Vector3(0.0f,0.0f,-_distance);
  this.Rotate(_x,_y);
 }
  
} //End class